kind: Service
apiVersion: v1
metadata:
  name: message-logger-api
  labels:
    app: message-logger
    tier: backend
spec:
  selector:
    app: message-logger
    tier: backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer
