kind: Service
apiVersion: v1
metadata:
  name: message-logger-frontend
  labels:
    app: message-logger
    tier: frontend
spec:
  selector:
    app: message-logger
    tier: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
